### ISSUE TITLE
Opening folders with `shellexecute-on-windows` feature doesn't respect to 'expand to open folder' setting

### ISSUE THREAD

**Issue by Legend-Master** [Byron/open-rs#103]
A small thing, after #98, when opening folders with the current implementation, the left panel of the file explorer will expand the folder to the current location, and I find it being quite annoying, the old implementation using `open` as operation (it's `explorer` now) doesn't have this problem

I found that using [`SHOpenFolderAndSelectItems`](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenfolderandselectitems) like this `SHOpenFolderAndSelectItems(folder, Some(&[folder]), 0)` will open that folder without expanding the left panel, and I don't think this will cause the explorer to freeze, do you think we can make a change to use it instead?

I'm willing to contribute the code if you will

**Comment by Byron** [comment]
Thanks for posting!

It's hard for me to understand why it would be annoying for lack of experience, but even without that it's clear that the new implementation has a side-effect and that could easily be considered unwanted.

Hence, I would be glad if you could come up with a fix and would appreciate screenshots of the before/after state of the explorer window for visualisation (and to satisfy my curiosity :)). Thank you.

**Comment by Legend-Master** [comment]
> It's hard for me to understand why it would be annoying for lack of experience

My bad, sorry didn't post screenshots for references, here you go

Current

![image](https://github.com/user-attachments/assets/8742bfd9-b810-4c5e-a66a-f10f2132716f)

Old

![image](https://github.com/user-attachments/assets/3d901c2c-2981-41cc-92b2-76879206b97e)

There is a setting for this behavior, the current implementation ignores this setting while the old one will not

![image](https://github.com/user-attachments/assets/99a82f5c-c755-4844-9356-6bec60595f6f)
