### ISSUE TITLE
Doesn't work on Windows if process exits shortly after calling open::that

### ISSUE THREAD

**Issue by kuviman** [Byron/open-rs#12]
Hello,

I am basically doing this:
```Rust
extern crate open;
fn main() {
    assert!(open::that("http://localhost").unwrap().success());
    std::thread::sleep_ms(1000);
}
```

So, if the sleep is removed, nothing is being opened.

**Comment by Fanaen** [comment]
Interestingly, it seems the problem happens only when running the program through Cargo. I am currently building a CLI app and I ran a few tests on my Windows 10 :

1. `cargo run` doesn't open the browser without `thread::sleep_ms` 
2. `cargo run` does open the browser with `thread::sleep_ms` and at least 50 as param
3. I tried multiple creation_flags (Windows specifics) and different output methods but none of them changed the outcome.
4. `cargo build` then `.\target\release\projectname.exe` does open the browser even without the `thread::sleep_ms`

My understanding of the Cargo + Windows environment is not enough to explain why it behaves like this. As for the fix, adding in the readme a simple warning about that very specific situation should be enough.

**Comment by Byron** [comment]
@Fanaen Thanks a lot for the summary! Do you think you could drop a PR which adds the information you would find helpful? Maybe as some sort of 'Caveats' section.

**Comment by kuviman** [comment]
I guess the reason is that `start` spawns child process, that is still running while the main program has exited already. For some reason `cargo run` kills it after exit.

Here is an example too see it more clearly:

1) create a binary `sleep-hello.exe` like this:
```rs
fn main() {
    std::thread::sleep_ms(3000);
    println!("Hello");
}
```

2) create a binary `open-test.exe`:
```rs
extern crate open;
fn main() {
    open::that("sleep-hello.exe");
    std::thread::sleep_ms(1000);
}
```

You will see that there is a `cmd.exe` instance running for only a second, and killed when `cargo` exits. Running without `cargo` (`.\target\release\open-test.exe`) works ok: `open-test.exe` exits after a second, but `cmd.exe` window is not killed and runs for 2 seconds more, as expected.

Back to the `http://localhost` example, try running that one with your browser closed before you run it. It doesn't matter what the sleep duration is, browser will still be closed after `cargo` exits.

**Comment by kuviman** [comment]
I've opened an issue in cargo repo: https://github.com/rust-lang/cargo/issues/5598

**Comment by Seeker14491** [comment]
This issue has been fixed; the given code works for me with or without the sleep.

**Comment by kuviman** [comment]
Indeed, works now
