### ISSUE TITLE
Support for Linux in WSL using wslu/wslview

### ISSUE THREAD

**Issue by timvisee** [Byron/open-rs#20]
Wouldn't it be nice to support Linux inside of [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) as well?

It looks like [`wslview`](https://github.com/wslutilities/wslu/wiki/wslview) (provided by [`wslu`](https://github.com/wslutilities/wslu)) can be used for this, which seems to be installed by default in most WSL distros these days and is otherwise easily installable.

I'm not entirely sure whether this supports opening paths (non URLs) as well right now, so that must be tested. I'll open an WIP PR for the time being.

**Comment by Byron-TW** [comment]
Thanks a lot :) ! I will be merging the PR once you think it's ready.

**Comment by timvisee** [comment]
Just gave it a test on a Windows machine. It appears that the `wslview` command is only limited to URLs. Opening a system path results in an error.

I therefore don't think it can be used as proper replacement as in the linked PR.

Would limiting `wslview` to URLs be an option? This could be implemented by checking whether a given url/path/input is considered an URL.

**Comment by Byron-TW** [comment]
Thanks for testing! I think it's OK to live with not supporting paths, under the assumption that `wslopen` is the last program tried.
I have also added a similar comment to the PR.
In general, I tend to keep this crate very simple without too much logic. However, if you think it's worth the additional effort and it can be implemented without regression, I am certainly not against adding more logic.

**Comment by timvisee** [comment]
@Byron-TW Cool.

I didn't notice it will just try every command until success (and thought it would just check if the binary existed). I'll move it to the back indeed. Assuming all previous commands fail when running Linux in WSL, that should be all right.
