### ISSUE TITLE
Several Improvements (well... see description)

### ISSUE THREAD

**Issue by hybras** [Byron/open-rs#25]
I [forked](https://github.com/hybras/open-rs) your project and made a bunch of changes. So far I've

- created os specific modules
- changed how `cfg(target_os)` was being used
- Made the unix variant use [`which`](https://crates.io/crates/which) to check for the different open handlers. 

I also plan to change the windows variant to call to `explorer.exe` using [`Command`](https://doc.rust-lang.org/stable/std/process/struct.Command.html) instead of [`winapi::um::shellapi::ShellExecuteW`](https://docs.rs/winapi/0.3.9/winapi/um/shellapi/fn.ShellExecuteW.html). This removes unsafe from `windows::that` and drastically simplifies the method.

I would like your feedback on my changes.

Whether you accept them or not, I love `open`! Previously I was using a shell function, which was very hacky not always portable.

**Comment by hoodie** [comment]
question: isn't xdg-open always available?

**Comment by hybras** [comment]
> question: isn't xdg-open always available?

You... are probably right. But by that logic, why are we checking for alternatives at all? Do u want me to special case `xdg-open`?

**Comment by Byron** [comment]
Will have a closer look later. In the meantime: Maybe also consult the ‘opener’ crate for reference.

**Comment by Byron** [comment]
Would you be OK to send a draft PR so I can have a look and potentially leave some comments?

**Comment by hybras** [comment]
Yes I'll do that. At time of writing i still haven't finished the last point I mentioned
