### ISSUE TITLE
url schemes

### ISSUE THREAD

**Issue by hoodie** [Byron/open-rs#3]
Hi there, I just had an idea, but can't test it on anything but linux.

You would not be able to tell if something like:

```rust
open::that("mailto:recipient@example.com");
```

would work on windows and mac as well?

**Comment by Byron** [comment]
**tl;dr** Yes, opening URLs works on all supported platforms.

Hi @hoodie, even though I cannot prove my statement, I am quite convinced that 'opening something based on a path or URL' is implemented by all platforms, provided the correct program is used. This is what `open-rs` is believed to be doing.

You might want to gain more confidence by checking the documentation of the `start` ,`open` and `"xdg-open", "gnome-open", "kde-open"`.
