### ISSUE TITLE
Support for gio open on Linux

### ISSUE THREAD

**Issue by City-busz** [Byron/open-rs#30]
On most Linux systems, the `gio` binary from `glib2` package is available to open URLs, e.g.:
`$ gio open https://github.com/`

It would be nice if this library would be able to use it.

**Comment by Byron** [comment]
You are welcome to append the program name to this list and submit a PR. Thanks

https://github.com/Byron/open-rs/blob/ccbae5d122cb0b8cff58d9125ced2d0211e82ec9/src/lib.rs#L255

**Comment by City-busz** [comment]
I opened a PR #31. It's a bit more complex, because the `gio` command requires an additional `open` argument. I put it before `gnome-open`, because `gio open` is meant to be a replacement for `gnome-open`. `gnome-open` is deprecated years ago, and cannot be found on modern Linux distributions.

**Comment by Byron** [comment]
Thanks for your help. 
v1.7 was just released, containing the change.
