### ISSUE TITLE
Files open in background

### ISSUE THREAD

**Issue by YesSeri** [Byron/open-rs#37]
I have a problem when opening local files on the computer like this.

```
match open::that(path) {
    Ok(()) => println!("Opened '{}' successfully.", path),
    Err(err) => panic!("An error occurred when opening '{}': {}", path, err),
}
```

The behaviour I expect is that the file should open in the foreground, so it becomes the active window and the file can be used immediately. What happens is however is that it opens furthest in the background. When I alt tab it is the last window that you get to. 

This is my experience on windows 10.

Is it supposed to be this way?

**Comment by YesSeri** [comment]
This doesn't happen when I make a minimal example like this:

```rust
fn main() {
	open::that("C:/Programming/rust/rust-in-action/file-open/test/pdf/test.pdf").unwrap();
}
```

I will dig into it a bit deeper and see why it is happening in my program that is a bit more complex. It might have something to do with the program being multithreaded? Or maybe there is a weird interaction with crossterm.

**Comment by Byron** [comment]
Thanks for letting me know!

Maybe you find what's causing the issue along with a workaround. If so, please let me know here or consider contributing a fix if feasible.

Good luck hunting.

**Comment by YesSeri** [comment]
This is what I have found out. The bug is because of an interaction with crossterm, and more exactly with the `crossterm::event::read()` function. This is two minimal examples:

What happens here is that the program waits one second for user actions and if the user presses a key it goes into the if statement and then repeats. This example works and the file gets opened in the foreground as soon as the user presses a key:
```rust
use crossterm::event::{poll, read, Event, KeyCode};
use std::time;

fn main() {
	loop {
		if poll(time::Duration::from_millis(1_000)).unwrap() {
			open::that("C:/Programming/rust/rust-in-action/Rust-In-Action.pdf").unwrap();
		}
	}
}

```
In this example I do the exact same thing, but I also read what key the user has pressed, and if it is `esc` I break the loop, which then quits the program. This example doesn't work as expected and the file gets opened furthest in the background when the user presses a key:
```rust
use crossterm::event::{poll, read, Event, KeyCode};
use std::time;

fn main() {
	loop {
		if poll(time::Duration::from_millis(1_000)).unwrap() {
			open::that("C:/Programming/rust/rust-in-action/Rust-In-Action.pdf").unwrap();
			let event = read().unwrap();
			if event == Event::Key(KeyCode::Esc.into()) {
				break;
			}
		}
	}
}
```

I am quite new to rust, so I don't really have any good ideas on how to debug this further. Do you have an idea? Is it crossterm or is it this crate that has the bug?

**Comment by Byron** [comment]
Great detective work!

> Do you have an idea? Is it crossterm or is it this crate that has the bug?

I'd put the finger on Windows ;). Joking aside, maybe try to sleep between the `open(…)` and the `read(…)` so that these are definitely not overlapping. After all, `open(…)` may trigger some other process that might open things while crossterm tries to `read()`, and who knows what kind of side-effects this may have.

If that would work, that might count as workaround and maybe leads to an investigation on how `read(…)` can possibly have such a side-effect.

**Comment by YesSeri** [comment]
The problem still remains, when I try to sleep in between. I have switched to a different console crate to see if that helps. It made no difference. 

```
use console::{Key, Term};
use std::thread;
use std::{path::Path, time::Duration};

fn main() {
    let stdout = Term::buffered_stdout();
    if let Ok(key) = stdout.read_key() {
        if key == Key::ArrowDown {
            println!("Pressed down");
        }
    }
    thread::sleep(Duration::from_millis(1000));
    open::that(Path::new(".\\aaa.txt")).unwrap();
}
```

I am at a loss here. If I read a key, then the file always gets opened in the background.
