### ISSUE TITLE
Failed to open file on manjaro system

### ISSUE THREAD

**Issue by simonfire007** [Byron/open-rs#38]
The possible reason is that the stderr pipeline is occupied. Modify the lib.rs file line 184  to 
`.stderr(Stdio::null()) `
or modify the line 195 to
` .and_then(|mut err| err.read_to_end(&mut stderr).ok())`
 Just normal

**Comment by Byron** [comment]
I took another look and agree the current implementation can deadlock, sorry for missing this during review.

A patch release was created to address this: https://github.com/Byron/open-rs/releases/tag/v2.0.2
