### ISSUE TITLE
Function to open in a new thread

### ISSUE THREAD

**Issue by antoyo** [Byron/open-rs#4]
Hello.
It would be nice to have a function to open the file in a new thread to avoid blocking the calling program.
Something like that:

``` rust
pub fn background_that(url: &str) {
    let url = url.to_string();
    thread::spawn(move ||
        open::that(url).ok()
    );
}
```

Thanks.

**Comment by Byron** [comment]
Good idea ! As you have basically written all the code already, would you be willing to write a simple test for it and contribute it via a PR ?
I could imagine some people would at least like to have the resulting thread in their control though.

**Comment by hoodie** [comment]
how about naming it `open::that_in_background` though? Just because it would be in line with the existing `open::that` tone.
