### ISSUE TITLE
Allow GET parameters

### ISSUE THREAD

**Issue by DenisKolodin** [Byron/open-rs#5]
Library doesn't allow URLs with GET parameters, because OS interpret `&` char.
I use `^` to escape `&` (inspired by [stackoverflow](http://stackoverflow.com/questions/1327431/how-do-i-escape-ampersands-in-batch-files)) as workaround, but it's not cross-platform approach to use `^` within urls.

For Windows we could replace char `&` to pair `^&`, but input has `OsStr` type which must be converted to **Unicode** `str`, but it's not 100% possible. Any ideas?

**Comment by Byron** [comment]
Can you provide an example, using the library, that shows the issue you describe?
The library does not use a shell to run commands, therefore the interpretation of `&` is impossible.

**Comment by DenisKolodin** [comment]
This code I use:
```
let url = format!("http://{}:{}/?cluster={}:{}^&token={}",
    static_host, static_port, cluster_host, cluster_port, token);
if open::that(&url).is_err() {
    println!("Please, open this URL with your browser: {}", &url);
}
```

If I remove `^` browser opens link without `token` parameter and the following `cmd`'s error prints to the shell:
```
'token' is not recognized as an internal or external command,
operable program or batch file.
```

I think that's because `cmd /C` actually interpret shell command `start <args>&<tail>`.

**Comment by Byron** [comment]
Thanks a lot for the clarification! Do you think you could contribute the fix for windows? I have no access to that OS, in fortunately.
For manual testing, you could then use the little program provided in main.rs

**Comment by DenisKolodin** [comment]
Ok, I'll send you PR which fixes it.
