### ISSUE TITLE
VSCodium doesn't open files

### ISSUE THREAD

**Issue by dimvoly** [Byron/open-rs#60]
Don't think it's the fault of this crate, but letting you know anyway.

When I run a test that opens a file, no errors are reported and no file is opened. Stepping through the code in debug, shows that everything is a success.

If I use a separate terminal to run the exact same test, file opens exactly as expected. In my case is a pdf with the default Ubuntu pdf viewer being opened.

Using Ubuntu 20.04 and VSCodium 1.74.1.
I suspect is a problem with VSCodium (or VSCode).

Perhaps there are some security settings somewhere I have to play with?

**Comment by Byron** [comment]
Could you try using [the `opener` crate](https://github.com/Seeker14491/opener)? I'd be interested to know if it has the same issue. If so, it's probably safe to assume it's something with VSCode, else it might be something that can be fixed here nonetheless.

**Comment by dimvoly** [comment]
Just tried it, and yes, same exact thing, fails silently in VSCodium, works fine from the terminal. So that rules out this crate then. I did raise an issue with [VSCodium](https://github.com/VSCodium/vscodium/issues/1354), although it is probably the fault of VSCode.

**Comment by dimvoly** [comment]
After various upgrades (VSCodium & rustc), including upgrading this `open` crate to "4.0.0", the PDF opens in system viewer if I go to the VSCodium terminal and run `cargo test` from there. If I click on the code lens shortcut to run a specific test, then same problem as before, system viewer doesn't open.

**Comment by Eusebius1920** [comment]
How do you open the pdf from the terminal?

**Comment by dimvoly** [comment]
> How do you open the pdf from the terminal?

In my code it is thus:
`open::that("file_to_open.pdf")`

That code resides in a rust test, which I can run with `cargo test` either via VSCodium's terminal, or via a separate terminal.
