### ISSUE TITLE
behaviour isn't the same as xdg-open (availability of terminal matters)

### ISSUE THREAD

**Issue by Cyrix126** [Byron/open-rs#61]
When using open::that on a text file, it opens with the browser.
When using Command::new("/usr/bin/xdg-open"), it opens with nano, same as doing it directly in terminal.

Here's complete example: (Artix linux):
```
xdg-open --version:
xdg-open 1.1.3+
```
```
~/.local/share/applications/nano.desktop:
[Desktop Entry]
Name=Nano
Exec=nano
Terminal=true
Type=Application
MimeType=text/plain;inode/x-empty
```
```
xdg-mime query default text/plain:
nano.desktop
```
```
xdg-mime query filetype ~/test.txt:
text/plain
```
```
test.txt:
hello
```
```
Cargo.toml:
[package]
name = "test_open"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "3.2.0"
```

```
src/main.rs:
use std::process::Command;

pub const XDG_PATH: &str = "/usr/bin/xdg-open";
fn main() {
    // open with nano as expected.
    let file = "test.txt";
    let mut open = Command::new(XDG_PATH);
    open.arg(file);
    open.spawn().unwrap();
    // open with browser
    open::that(file).unwrap();
}
```

I'm not sure why the issue exist, looking at the code of the lib I don't see why it behaves differently if it is just executing also a Command.

**Comment by Byron** [comment]
Thanks for posting and for providing all the information that would be needed for a reproduction, much appreciated.

The difference I see is that one uses the full path to the binary, the other searches in `PATH`, i.e. the difference between `Command::new("/usr/bin/xdg-open")` and `Command::new("xdg-open")`. Everything else seems indeed to be the same, so maybe for some reason there is another `xdg-open` in the `PATH`?

**Comment by Cyrix126** [comment]
Hi, thanks for the response.
which xdg-open locate the same executable.
`/usr/bin/xdg-open`



> When using Command::new("/usr/bin/xdg-open"), it opens with nano, **same as doing it directly in terminal.**

**Comment by Cyrix126** [comment]
Just a guess but maybe it is related to nano being a terminal app.
It opens with xdg-open but because there is already a terminal open. Maybe xdg-open fallback for the browser (firefox in this case).

**Comment by Byron** [comment]
Thanks for letting me know.

What happens if you change the example to this?

```Rust
src/main.rs:
use std::process::Command;

pub const XDG_PATH: &str = "/usr/bin/xdg-open";
fn main() {
    // open with nano as expected.
    let file = "test.txt";
    let mut open = Command::new(XDG_PATH);
    open.arg(file);
    open.status_without_output().unwrap();
    // open with browser
    open::that(file).unwrap();
}
```

Maybe the configuration of stdout affects it? If there is no stdout, it can't see it runs in a terminal, and will use the browser instead.

**Comment by Cyrix126** [comment]
`status_without_output` is a method that exist in the open/src/lib.rs, but it doesn't exist for std::process::Command by default.
```Rust
use std::{
    io,
    process::{Command, Stdio},
};

pub const XDG_PATH: &str = "/usr/bin/xdg-open";

trait CommandExt {
    fn status_without_output(&mut self) -> io::Result<std::process::ExitStatus>;
}

impl CommandExt for Command {
    fn status_without_output(&mut self) -> io::Result<std::process::ExitStatus> {
        let mut process = self
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()?;

        process.wait()
    }
}

fn main() {
    // open with nano as expected.
    let file = "test.txt";
    let mut open = Command::new(XDG_PATH);
    open.arg(file);
    open.status_without_output().unwrap();
    // open with browser
    open::that(file).unwrap();
}

```

With this code indeed it is the same behaviour, the browser is used.
A little workaround is to set ~/.local/share/applications/nano.desktop to use a terminal, like
`Exec= foot nano`
instead of 
`Exec=nano`

But of course it opens nano in a new terminal and not in the same that you run the program.

**Comment by Byron** [comment]
Great to hear a workaround _somewhat_ exists. Even if output would be collected `xdg-open` would see that it's not connected to a terminal and act the same. Thus I don't think there is way to effectively trigger that behaviour unless of course, one would use `xdg-open` directly if it is a requirement.

I am closing this issue as opening the browser is what I had in mind for this crate anyway, and it's good to know that this isn't necessarily the case depending on usage.
