### ISSUE TITLE
Opening url on windows with multiple query params

### ISSUE THREAD

**Issue by Eusebius1920** [Byron/open-rs#67]
```rust
let url = "https://archlinux.org/packages/?sort=&q=test&maintainer=&flagged=";
open::that(url).unwrap();
```

opens on windows a browser with the factual url:
`https://archlinux.org/packages/?sort=` (cut off at the first ampersand &)

The code above panics with result:

```
Launcher \"cmd\" \"/c\" \"start\" \"https://archlinux.org/packages/?sort=&q=test&maintainer=&flagged=\" failed with ExitStatus(ExitStatus(1))
```

Executing this "manually" in the terminal:
```
> cmd /c start "https://archlinux.org/packages/?sort=&q=test&maintainer=&flagged="
the command "q" is either misspelled or could not be found
the command "maintainer" is either misspelled or could not be found
the command "flagged" is either misspelled or could not be found
```

**Workaround**:
```rust
let url = "https://archlinux.org/packages/?sort=&q=test&maintainer=&flagged=";
open::that(url.replace('&', "^&")).unwrap();
```
works because `^&` can be used to escape ampersands in commands.

**Comment by Byron** [comment]
Thanks so much for this wonderful issue - it describes the problem *and* proposes a solution.

It's interesting that each windows command seems to do its very own parsing, and despite the path being passed as separate argument it tries to interpret it. Worse, it seems to try to execute commands.

If you think that doing such a replacement by default, would you be interested in submitting a PR for a fix?
