### ISSUE TITLE
Converts # into %0A%23

### ISSUE THREAD

**Issue by benmanone** [Byron/open-rs#77]
If I write:
`open::that("https://en.wiktionary.org/wiki/open#Finnish");`
The crate attempts to open https://en.wiktionary.org/wiki/open%0A%23Finnish (which is invalid).
How can I prevent it from doing this?
Thanks in advance

**Comment by Byron** [comment]
I cannot reproduce this on MacOS or Windows using the latest version from `main` and `cargo run -- "https://en.wiktionary.org/wiki/open#Finnish"`.

Maybe an older version is used? No such conversion is done anywhere in recent code as far as I can see.
Please feel free to keep posting, and the issue can be reopened once it's reproduced. Thanks for your understanding.
