### ISSUE TITLE
Use PowerShell Command in Windows

### ISSUE THREAD

**Issue by psobolik** [Byron/open-rs#95]
Since PowerShell has been the default shell in Windows since Windows 10, I wonder if `open-rs` ought to prefer it over `cmd`? I worked out an implementation of the `command` function in `windows.rs` that the returns commands that will execute `pwsh`, `cwd` and `powershell`. I would be happy to submit a pull request if you are interested. (I haven't checked, but I suspect this might address issue https://github.com/Byron/open-rs/issues/73 as well.)

**Comment by Byron** [comment]
Thanks for bringing this idea forward, and for implementing it so there would be something to test.

My main concern here would be compatibility, and secondarily performance. Compatibility might be the reason that this implementation would have to go behind a feature toggle for a while so applications can opt-in, all under the assumption that it solves a real problem, like maybe #73.

If it would do the same, but differently, I think in the name of compatibility the current implementation should be kept.
Maybe there are other advantages that you can find as well, all reason enough to make it available behind a feature toggle.

**Comment by psobolik** [comment]
I was able to duplicate the problem with VSCode described in https://github.com/Byron/open-rs/issues/73, and my changes don't help; both versions of PowerShell work the same as `cmd`, which is to say that they don't fail, but don't open anything, either. I think the approach in pull request https://github.com/Byron/open-rs/pull/75 is on the right track, although I think it should be trying to run `explorer` (`alt_cmd`) _before_ `cmd`.

Since it doesn't really add anything, I guess trying PowerShell over cmd  is probably a solution looking for a problem, and I'm closing it.

**Comment by Byron** [comment]
Thanks again for investigating this! 

I wasn't even aware of #75 anymore and hoped you could pick it up and change the order in your own PR? If that fixes #73, we'd have a win here :)
